# {{- if not .Values.externalSecrets.enabled }}
# Only create this secret if not using External Secrets
apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
  namespace: {{ .Release.Namespace }}
stringData:
  POSTGRES_DB: {{ .Values.postgresql.global.postgresql.auth.database | quote }}
  POSTGRES_PASSWORD: {{ .Values.postgresql.global.postgresql.auth.password | quote }}
type: Opaque
# {{- end }}