ingress:
  hostnames:
    - dev.inferno.sparked-fhir.com
    - inferno.dev.hl7.org.au

inferno:
  imageUrl: ghcr.io/hl7au/au-fhir-inferno:7a78c7ce86294055090ae7379ba3eefd1f6f128f-dev
  usesWrapper: true
  validatorImageUri: markiantorno/validator-wrapper:latest

nginx:
  platformImageUri: ghcr.io/hl7au/au-fhir-inferno:7a78c7ce86294055090ae7379ba3eefd1f6f128f-nginx-dev


externalSecrets:
  enabled: true
  roleArn: arn:aws:iam::471112546300:role/dev-sparkey-inferno-external-secrets-sa
  secretArn: arn:aws:secretsmanager:ap-southeast-2:471112546300:secret:rds!db-ed54d45e-936a-4cf0-bdbb-9356864d6670-3FhA4J
  username: postgres  # Since username isn't sensitive, we can hardcode it
  region: ap-southeast-2

postgresql:
  externaldbhost: dev-sparkey-inferno-postgresql.creaskuwcgs3.ap-southeast-2.rds.amazonaws.com
  global:
    postgresql:
      auth:
        database: inferno