ingress:
  hostnames:
    - inferno.sparked-fhir.com
    - inferno.hl7.org.au

redirectIngress:
  enabled: true
  hostnames:
    - inferno.dev.hl7.org.au
  targetUrl: "https://inferno.hl7.org.au"

inferno:
  imageUrl: ghcr.io/hl7au/au-fhir-inferno:277a9d980a95811b9ac84ccd2c255d16e1adee35-prod
  usesWrapper: true
  validatorImageUri: markiantorno/validator-wrapper:latest

nginx:
  platformImageUri: ghcr.io/hl7au/au-fhir-inferno:277a9d980a95811b9ac84ccd2c255d16e1adee35-nginx-prod


externalSecrets:
  enabled: true
  roleArn: arn:aws:iam::471112546300:role/prod-inferno-external-secrets-sa
  secretArn: arn:aws:secretsmanager:ap-southeast-2:471112546300:secret:rds!db-4a252b41-3b6b-475b-9b8c-161589839fe3-QZ8sT1
  username: postgres
  region: ap-southeast-2

postgresql:
  externaldbhost: prod-inferno-postgresql.creaskuwcgs3.ap-southeast-2.rds.amazonaws.com
  global:
    postgresql:
      auth:
        database: inferno