{{- if .Values.redirectIngress.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: redirect-nginx
  namespace: {{ .Values.namespace }}
  labels:
    app: redirect-nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
  selector:
    app: redirect-nginx
{{- end }}
